

development:
  adapter: sqlite3
  encoding: unicode
  database: development
  username: root
  password: admin
  host: localhost

#production:
 # adapter: postgresql
  #encoding: unicode
  #pool: 5
  #host: <%= ENV['DATABASE_HOST'] %>
  #database: <%= ENV['DATABASE_NAME'] %>
  #username: <%= ENV['DATABASE_USER'] %>
  #password: <%= ENV['DATABASE_PASSWORD'] %>